### ISSUE TITLE
Loading modules.

### ISSUE THREAD

**Issue by mrwert** [kilpatds/PluginFramework#4]
Hello!
How to load multiple modules?
Thanks!

**Comment by kilpatds** [comment]
Call "getPlugin()" multiple times with different names of plugins?

The getPlugin() call ends up returning a new object (from the named type).  I changed base_test to load in all the plugins named, and:

[kilpatds@hawke base_test]$ ./baseTest Foo Bar
Foo::print
Bar::print

**Comment by mrwert** [comment]
I understood.
eee
Thanks!
